//! Conductor System Types
//!
//! Models for tasks, plans, memory, and orchestration.

use serde::{Deserialize, Serialize};

/// Budget allocation for a single LLM request
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryBudget {
    /// Token limit for system instructions
    pub system_tokens: usize,
    /// Token limit for retrieved project context
    pub project_tokens: usize,
    /// Token limit for retrieved episodic memory
    pub episodic_tokens: usize,
    /// Token limit for recent conversation history
    pub session_tokens: usize,
    /// Total max tokens (sum of above + safety margin)
    pub total_limit: usize,
}

impl Default for MemoryBudget {
    fn default() -> Self {
        Self {
            system_tokens: 1000,
            project_tokens: 2000,
            episodic_tokens: 1000,
            session_tokens: 4000,
            total_limit: 8192,
        }
    }
}

/// A high-level plan generated by the Planner
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConductorPlan {
    pub id: String,
    pub original_goal: String,
    pub steps: Vec<PlanStep>,
    pub created_at: i64,
}

/// A single step within a ConductorPlan
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub id: String,
    pub description: String,
    pub step_type: StepType,
    pub dependencies: Vec<String>,
    pub expected_outcome: String,
}

/// The varying types of work the Conductor orchestrates
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum StepType {
    /// Investigate codebase, search files, read logs
    Research,
    /// Write files, execute commands, modify state
    Execute,
    /// Run tests, lint, review changes
    Verify,
}

/// The result of executing a PlanStep
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StepResult {
    pub step_id: String,
    pub success: bool,
    pub tools_used: Vec<String>,
    pub logs: String,
    pub context_extracted: String,
}
